Repository GitNether/paperback, pull requests merged in 2024-06, with the labels that each got.

#4 Add calling card
  README.md
  assets/1x/Jokers.png
  assets/2x/Jokers.png
  assets/shaders/hologramv2.fs
  joker/calling_card.lua
  joker/pool_table.lua
  paperback.lua
Labels: implementation

#10 Replace `require` for `NFS.load(path)()`, and add `.lua` at the end of…
  paperback.lua
Labels: bugfix

#8 Implement Ghost Cola
  joker/ghost_cola.lua
  paperback.lua
Labels: implementation, needs fix

#9 Add "Ghost Cola" to README
  README.md
Labels: documentation
