Repository GitNether/paperback, pull requests merged in 2024-08, with the labels that each got.

#14 Implement a website for the mod
  .vscode/settings.json
  docs/LICENSE
  docs/addjokers.js
  docs/img/favicon.ico
  docs/img/j_calling_card.png
  docs/img/j_derecho.png
  docs/img/j_forgery.png
  docs/img/j_furioso.png
  docs/img/j_ghost_cola.png
  docs/img/j_hole_in_one.png
  docs/img/j_joker.png
  docs/img/j_mismatched_sock.png
  docs/img/j_nachos.png
  docs/img/j_pool_table.png
  docs/img/j_pride_flag.png
  docs/img/j_quick_fix.png
  docs/img/j_sacrificial_lamb.png
  docs/img/j_shopping_center.png
  docs/img/j_skydiver.png
  docs/img/j_solar_system.png
  docs/img/j_solemn_lament.png
  docs/img/j_stamp.png
  docs/img/j_summoning_circle.png
  docs/img/j_union_card.png
  docs/img/j_wish_you_were_here.png
  docs/img/s_seal.png
  docs/img/sticker_bg.png
  docs/img/sticker_example.png
  docs/img/the_wall.png
  docs/img/violet_vessel.png
  docs/index.html
  docs/m6x11plus.ttf
  docs/style.css
Labels: documentation

#13 Update README.md
  README.md
Labels: documentation

#12 Implement `Nachos`
  joker/nachos.lua
  paperback.lua
Labels: implementation

#7 Sacrificial lamb joker
  README.md
  docs/addjokers.js
  joker/sacrificial_lamb.lua
  paperback-utils.lua
  paperback.lua
Labels: implementation, needs fix
