Repository GitNether/paperback, pull requests merged in 2025-02, with the labels that each got.

#132 (Skydiver) Add support for modded ranks
  .vscode/settings.json
  joker/skydiver.lua
  paperback-utils.lua
Labels: bugfix, cross-mod integration

#136 (Joker) Implement Pocket Pair
  joker/pocket_pair.lua
  localization/en-us.lua
  paperback.lua
Labels: implementation

#135 (Joker) Implement Champagne
  joker/champagne.lua
  localization/en-us.lua
  paperback.lua
Labels: implementation, awaiting artwork

#137 Add a config interface
  config.lua
  localization/en-us.lua
  paperback-utils.lua
  paperback.lua
Labels: implementation

#138 Implement modded light & dark suits
  joker/paranoia.lua
  joker/union_card.lua
  localization/en-us.lua
  paperback-utils.lua
  paperback.lua
Labels: implementation, cross-mod integration

#144 Add utility function for changing a card's sell value
  joker/hole_in_one.lua
  joker/wish_you_were_here.lua
  paperback-utils.lua
Labels: bugfix

#143 Add Food pool
  joker/apple.lua
  joker/cakepop.lua
  joker/caramel_apple.lua
  joker/champagne.lua
  joker/charred_marshmallow.lua
  joker/coffee.lua
  joker/complete_breakfast.lua
  joker/cream_liqueur.lua
  joker/crispy_taco.lua
  joker/dreamsicle.lua
  joker/epic_sauce.lua
  joker/ghost_cola.lua
  joker/joker_cookie.lua
  joker/nachos.lua
  joker/soft_taco.lua
  paperback-utils.lua
Labels: cross-mod integration

#140 First implementation of Minor Arcana
  config.lua
  localization/en-us.lua
  minor_arcana/two_of_cups.lua
  paperback-utils.lua
  paperback.lua
Labels: implementation

#151 (Joker) Implement "Ice Cube"
  joker/ice_cube.lua
  localization/en-us.lua
  paperback-utils.lua
  paperback.lua
Labels: implementation

#155 Add enhancements and related minor arcana cards
  config.lua
  content/enhancement/porcelain.lua
  content/enhancement/soaked.lua
  content/minor_arcana/five_of_cups.lua
  content/minor_arcana/queen_of_cups.lua
  localization/en-us.lua
  paperback.lua
  utilities/definitions.lua
  utilities/ui.lua
Labels: implementation

#158 (Friends of Paperback) Add the first set
  assets/1x/deckskin_set1_hc.png
  assets/1x/deckskin_set1_lc.png
  assets/2x/deckskin_set1_hc.png
  assets/2x/deckskin_set1_lc.png
  content/friends_of_paperback/set1.lua
  paperback.lua
  utilities/definitions.lua
  utilities/misc_functions.lua
Labels: implementation
